Repository TycheSoftwares/order-delivery-date-for-woocommerce, pull requests merged in 2018-06, with the labels that each got.

#134 Changed the class name in template file of Deactivate popup modal
  order-delivery-date-for-woocommerce/includes/component/deactivate-survey-popup/template/ts-deactivate-modal.php
Labels: GDPR

#136 Fix #135
  order-delivery-date-for-woocommerce/integration.php
Labels: Client Issue, bug

#137 Fix #105
  order-delivery-date-for-woocommerce/languages/messages.pot
  order-delivery-date-for-woocommerce/languages/order-delivery-date.mo
  order-delivery-date-for-woocommerce/languages/order-delivery-date.po
  order-delivery-date-for-woocommerce/orddd-lite-settings.php
Labels: bug

#138 Fix #104
  order-delivery-date-for-woocommerce/orddd-lite-common.php
Labels: Client Issue, bug

#139 Fix #118
  order-delivery-date-for-woocommerce/js/orddd-lite-initialize-datepicker.js
Labels: Auto-populate, bug, holiday

#140 Fix #103
  order-delivery-date-for-woocommerce/orddd-lite-settings.php
Labels: bug
